package com.aionemu.gameserver.world.geo.navmesh;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.PriorityQueue;
import java.util.Set;

import com.aionemu.gameserver.geoEngine.math.Vector3f;

/** Immutable AL40 navigation data generated by ALGeoBuilder. */
public final class Al40NavMesh {

	private static final int[][] DIRECTIONS = {
		{ 0, 1 }, { 1, 1 }, { 1, 0 }, { 1, -1 },
		{ 0, -1 }, { -1, -1 }, { -1, 0 }, { -1, 1 }
	};
	private static final float SQRT_2 = 1.41421356f;
	private final int worldId;
	private final List<Subgraph> subgraphs;
	private final long floorCount;

	Al40NavMesh(int worldId, List<Subgraph> subgraphs, long floorCount) {
		this.worldId = worldId;
		this.subgraphs = List.copyOf(subgraphs);
		this.floorCount = floorCount;
	}

	public int worldId() {
		return worldId;
	}

	public int subgraphCount() {
		return subgraphs.size();
	}

	public long floorCount() {
		return floorCount;
	}

	public PathResult findPath(Vector3f start, Vector3f goal, int maxVisitedNodes) {
		List<LocatedFloor> starts = findFloors(start.x, start.y, start.z);
		List<LocatedFloor> goals = findFloors(goal.x, goal.y, goal.z);
		if (starts.isEmpty() || goals.isEmpty())
			return PathResult.empty(0);

		List<FloorPair> candidates = new ArrayList<>();
		for (LocatedFloor startFloor : starts) {
			for (LocatedFloor goalFloor : goals) {
				if (startFloor.subgraphIndex == goalFloor.subgraphIndex)
					candidates.add(new FloorPair(startFloor, goalFloor));
			}
		}
		candidates.sort(Comparator.comparingDouble(pair -> pair.verticalError(start.z, goal.z)));

		int visited = 0;
		for (FloorPair candidate : candidates) {
			PathResult result = findPath(candidate.start, candidate.goal, goal, Math.max(1, maxVisitedNodes - visited));
			visited += result.visitedNodes;
			if (result.complete)
				return new PathResult(result.points, true, visited);
			if (visited >= maxVisitedNodes)
				return PathResult.empty(visited);
		}
		return PathResult.empty(visited);
	}

	public boolean contains(float x, float y, float z) {
		return !findFloors(x, y, z).isEmpty();
	}

	private PathResult findPath(LocatedFloor locatedStart, LocatedFloor locatedGoal, Vector3f requestedGoal, int maxVisitedNodes) {
		Subgraph graph = subgraphs.get(locatedStart.subgraphIndex);
		Floor start = locatedStart.floor;
		Floor goal = locatedGoal.floor;
		if (start.equals(goal))
			return new PathResult(List.of(new Vector3f(requestedGoal.x, requestedGoal.y, goal.z)), true, 0);

		PriorityQueue<OpenNode> open = new PriorityQueue<>(Comparator.comparingDouble(OpenNode::f));
		Map<Long, Float> scores = new HashMap<>();
		Map<Long, Long> parents = new HashMap<>();
		Set<Long> closed = new HashSet<>();
		long startKey = start.key();
		scores.put(startKey, 0f);
		open.add(new OpenNode(start, 0, heuristic(graph, start, goal)));
		int visited = 0;

		while (!open.isEmpty() && visited < maxVisitedNodes) {
			OpenNode entry = open.poll();
			Floor current = entry.floor;
			long currentKey = current.key();
			Float bestScore = scores.get(currentKey);
			if (bestScore == null || entry.g > bestScore || !closed.add(currentKey))
				continue;
			visited++;
			if (current.equals(goal))
				return new PathResult(reconstruct(graph, parents, start, goal, requestedGoal), true, visited);

			for (int direction = 0; direction < DIRECTIONS.length; direction++) {
				Floor neighbour = graph.neighbour(current, direction);
				if (neighbour == null || closed.contains(neighbour.key()))
					continue;
				float tentative = bestScore + ((direction & 1) == 0 ? 1 : SQRT_2);
				Float oldScore = scores.get(neighbour.key());
				if (oldScore != null && tentative >= oldScore)
					continue;
				scores.put(neighbour.key(), tentative);
				parents.put(neighbour.key(), currentKey);
				open.add(new OpenNode(neighbour, tentative, tentative + heuristic(graph, neighbour, goal)));
			}
		}
		return PathResult.empty(visited);
	}

	private List<Vector3f> reconstruct(Subgraph graph, Map<Long, Long> parents, Floor start, Floor goal, Vector3f requestedGoal) {
		List<Vector3f> reversed = new ArrayList<>();
		long key = goal.key();
		while (key != start.key()) {
			int blockIndex = (int) (key >>> 16);
			int encodedZ = (int) key & 0xFFFF;
			reversed.add(new Vector3f(graph.worldX(graph.blockX(blockIndex)), graph.worldY(graph.blockY(blockIndex)), graph.decodeZ(encodedZ)));
			Long parent = parents.get(key);
			if (parent == null)
				return List.of();
			key = parent;
		}
		Collections.reverse(reversed);
		if (!reversed.isEmpty())
			reversed.set(reversed.size() - 1, new Vector3f(requestedGoal.x, requestedGoal.y, goal.z));
		return simplify(reversed);
	}

	private List<Vector3f> simplify(List<Vector3f> path) {
		if (path.size() < 3)
			return path;
		List<Vector3f> result = new ArrayList<>();
		result.add(path.getFirst());
		int previousDx = Integer.signum(Math.round(path.get(1).x - path.get(0).x));
		int previousDy = Integer.signum(Math.round(path.get(1).y - path.get(0).y));
		for (int i = 1; i < path.size() - 1; i++) {
			int dx = Integer.signum(Math.round(path.get(i + 1).x - path.get(i).x));
			int dy = Integer.signum(Math.round(path.get(i + 1).y - path.get(i).y));
			if (dx != previousDx || dy != previousDy || Math.abs(path.get(i + 1).z - path.get(i).z) > 0.5f)
				result.add(path.get(i));
			previousDx = dx;
			previousDy = dy;
		}
		result.add(path.getLast());
		return result;
	}

	private float heuristic(Subgraph graph, Floor from, Floor goal) {
		int dx = Math.abs(graph.blockX(from.blockIndex) - graph.blockX(goal.blockIndex));
		int dy = Math.abs(graph.blockY(from.blockIndex) - graph.blockY(goal.blockIndex));
		return Math.max(dx, dy) + (SQRT_2 - 1) * Math.min(dx, dy);
	}

	private List<LocatedFloor> findFloors(float x, float y, float z) {
		List<LocatedFloor> result = findFloorsExact(x, y, z);
		if (!result.isEmpty())
			return result;
		for (int graphIndex = 0; graphIndex < subgraphs.size(); graphIndex++) {
			Subgraph graph = subgraphs.get(graphIndex);
			float halfStep = graph.step * 0.5f;
			float[][] offsets = {
				{ halfStep, 0 }, { -halfStep, 0 }, { 0, halfStep }, { 0, -halfStep },
				{ halfStep, halfStep }, { halfStep, -halfStep }, { -halfStep, halfStep }, { -halfStep, -halfStep },
				{ graph.step, 0 }, { -graph.step, 0 }, { 0, graph.step }, { 0, -graph.step }
			};
			for (float[] offset : offsets) {
				Floor floor = graph.floorAt(x + offset[0], y + offset[1], z);
				if (floor != null) {
					result.add(new LocatedFloor(graphIndex, floor));
					break;
				}
			}
		}
		return result;
	}

	private List<LocatedFloor> findFloorsExact(float x, float y, float z) {
		List<LocatedFloor> result = new ArrayList<>();
		for (int i = 0; i < subgraphs.size(); i++) {
			Floor floor = subgraphs.get(i).floorAt(x, y, z);
			if (floor != null)
				result.add(new LocatedFloor(i, floor));
		}
		return result;
	}

	public record PathResult(List<Vector3f> points, boolean complete, int visitedNodes) {
		public PathResult {
			points = List.copyOf(points);
		}

		static PathResult empty(int visitedNodes) {
			return new PathResult(List.of(), false, visitedNodes);
		}
	}

	static final class Subgraph {
		final int width;
		final int height;
		final float step;
		final float maxZStep;
		final float minX;
		final float minY;
		final int minZ;
		final int maxZ;
		final int[] grid;
		final byte[] multiHeights;

		Subgraph(int width, int height, float step, float maxZStep, float minX, float minY, int minZ, int maxZ, int[] grid,
			byte[] multiHeights) {
			this.width = width;
			this.height = height;
			this.step = step;
			this.maxZStep = maxZStep;
			this.minX = minX;
			this.minY = minY;
			this.minZ = minZ;
			this.maxZ = maxZ;
			this.grid = grid;
			this.multiHeights = multiHeights;
		}

		Floor floorAt(float x, float y, float z) {
			if (x < minX || y < minY || x >= minX + width * step || y >= minY + height * step)
				return null;
			int blockX = (int) ((x + step * 0.5f - minX) / step);
			int blockY = (int) ((y + step * 0.5f - minY) / step);
			if (blockX < 0 || blockX >= width || blockY < 0 || blockY >= height)
				return null;
			return closestFloor(blockY * width + blockX, z, 20, 4);
		}

		Floor neighbour(Floor current, int direction) {
			if ((current.flags & 1 << direction) != 0)
				return null;
			int x = blockX(current.blockIndex) + DIRECTIONS[direction][0];
			int y = blockY(current.blockIndex) + DIRECTIONS[direction][1];
			if (x < 0 || x >= width || y < 0 || y >= height)
				return null;
			float tolerance = maxZStep + 1;
			return closestFloor(y * width + x, current.z, tolerance, tolerance);
		}

		private Floor closestFloor(int blockIndex, float z, float downTolerance, float upTolerance) {
			int entry = grid[blockIndex];
			int count = entry >>> 24;
			if (count == 0)
				return null;
			Floor best = null;
			float bestDistance = Math.max(downTolerance, upTolerance);
			if (count == 1) {
				int flags = entry >>> 16 & 0xFF;
				float floorZ = decodeZ(entry & 0xFFFF);
				float difference = z - floorZ;
				if (flags != 0xFF && difference >= -upTolerance && difference <= downTolerance)
					best = new Floor(blockIndex, entry & 0xFFFF, flags, floorZ);
			} else {
				int offset = entry & 0xFFFFFF;
				for (int i = 0; i < count && offset + 2 < multiHeights.length; i++, offset += 3) {
					int flags = multiHeights[offset] & 0xFF;
					int encodedZ = (multiHeights[offset + 1] & 0xFF) | (multiHeights[offset + 2] & 0xFF) << 8;
					float floorZ = decodeZ(encodedZ);
					float difference = z - floorZ;
					float distance = Math.abs(difference);
					if (flags != 0xFF && difference >= -upTolerance && difference <= downTolerance && distance < bestDistance) {
						bestDistance = distance;
						best = new Floor(blockIndex, encodedZ, flags, floorZ);
					}
				}
			}
			return best;
		}

		float decodeZ(int encodedZ) {
			return minZ + (encodedZ & 0xFFFF) * (maxZ - minZ) / 65535f;
		}

		int blockX(int blockIndex) {
			return blockIndex % width;
		}

		int blockY(int blockIndex) {
			return blockIndex / width;
		}

		float worldX(int blockX) {
			return minX + blockX * step;
		}

		float worldY(int blockY) {
			return minY + blockY * step;
		}
	}

	private record LocatedFloor(int subgraphIndex, Floor floor) {
	}

	private record FloorPair(LocatedFloor start, LocatedFloor goal) {
		float verticalError(float startZ, float goalZ) {
			return Math.abs(startZ - start.floor.z) + Math.abs(goalZ - goal.floor.z);
		}
	}

	private record Floor(int blockIndex, int encodedZ, int flags, float z) {
		long key() {
			return (long) blockIndex << 16 | encodedZ & 0xFFFFL;
		}

		@Override
		public boolean equals(Object object) {
			return object instanceof Floor other && blockIndex == other.blockIndex && encodedZ == other.encodedZ;
		}

		@Override
		public int hashCode() {
			return blockIndex * 65537 + encodedZ;
		}
	}

	private record OpenNode(Floor floor, float g, float f) {
	}
}
