package com.aionemu.gameserver.world.geo.navmesh;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Stream;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.aionemu.gameserver.geoEngine.math.Vector3f;
import com.aionemu.gameserver.world.geo.navmesh.Al40NavMesh.PathResult;

/** Loads and serves AL40 navigation meshes generated by ALGeoBuilder. */
public final class NavMeshService {

	private static final Logger log = LoggerFactory.getLogger(NavMeshService.class);
	private static final Path NAVMESH_DIRECTORY = Path.of("data/geo");

	private volatile Map<Integer, Al40NavMesh> meshes = Map.of();

	public void init() {
		if (!Files.isDirectory(NAVMESH_DIRECTORY)) {
			log.warn("Navmesh directory {} does not exist; NPCs will use legacy movement", NAVMESH_DIRECTORY);
			return;
		}
		Map<Integer, Al40NavMesh> loaded = new ConcurrentHashMap<>();
		try (Stream<Path> files = Files.list(NAVMESH_DIRECTORY)) {
			files.filter(Files::isRegularFile).filter(path -> path.getFileName().toString().endsWith(".nav")).sorted().parallel()
				.forEach(path -> {
					String filename = path.getFileName().toString();
					try {
						int worldId = Integer.parseInt(filename.substring(0, filename.length() - 4));
						Al40NavMesh mesh = Al40NavMeshLoader.load(worldId, path);
						loaded.put(worldId, mesh);
						log.info("Loaded AL40 navmesh {}: {} subgraphs, {} floors, {} MB", worldId, mesh.subgraphCount(),
							mesh.floorCount(), Files.size(path) / 1024 / 1024);
					} catch (NumberFormatException e) {
						log.warn("Ignoring navmesh with non-numeric name: {}", filename);
					} catch (IOException | RuntimeException e) {
						log.error("Could not load navmesh " + path, e);
					}
				});
		} catch (IOException e) {
			log.error("Could not scan " + NAVMESH_DIRECTORY + " for navmeshes", e);
		}
		meshes = Map.copyOf(loaded);
		log.info("Loaded {} AL40 navmesh worlds", meshes.size());
	}

	public boolean hasNavMesh(int worldId) {
		return meshes.containsKey(worldId);
	}

	public PathResult findPath(int worldId, Vector3f start, Vector3f goal, int maxVisitedNodes) {
		Al40NavMesh mesh = meshes.get(worldId);
		return mesh == null ? PathResult.empty(0) : mesh.findPath(start, goal, maxVisitedNodes);
	}

	public boolean contains(int worldId, float x, float y, float z) {
		Al40NavMesh mesh = meshes.get(worldId);
		return mesh != null && mesh.contains(x, y, z);
	}

	public static NavMeshService getInstance() {
		return Holder.INSTANCE;
	}

	private static final class Holder {
		private static final NavMeshService INSTANCE = new NavMeshService();
	}
}
