gameserver.webshop.api.enable=true
gameserver.webshop.api.bind_address=127.0.0.1
gameserver.webshop.api.port=8099
gameserver.webshop.api.secret=+0tw/NaoGRdTbWBmAGn2Ta2u1eVx/JOAyQHMLsKB/Yc=
gameserver.webshop.api.allowed_addresses=127.0.0.1
gameserver.webshop.delivery.processing_timeout_seconds=120